### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by SylveonBottle** [Hypnootize/sunsethud#11]
https://github.com/Hypnootize/sunsethud/wiki/Streamer-HUD#:~:text=STREAMER%20MODE%20DO%3F-,The%20treamer%20mode,-aims%20to%20remove

"The treamer mode"

Tried to fork & edit myself for a PR, but I've just found out github doesn't support wiki forking.

**Comment by Hypnootize** [comment]
Thank you! there are probably a lot more :D
