### ISSUE TITLE
Inventory screens displaying blank in x64 test

### ISSUE THREAD

**Issue by leo-proct** [Hypnootize/sunsethud#15]
Not sure if it was addressed in the latest patch note "Updated HUD to support last TF2 updates"

But any backpack related screen still remains blank

**Comment by Hypnootize** [comment]
It wasn't, I honestly forgot to test any of my HUDs for the x64 beta.

It seems to be related to `Resource/UI/CharInfoPanel.res` and I was able to fix it pretty quickly by changing both `"settitlebarvisible"` to `"1"` and under `"Sheet"` edit `"yoffset"` to `"13"`

This doesn't seem to be a problem on the 32 bit version which is pretty interesting to me. Did you notice any other bug?

**Comment by leo-proct** [comment]
Let me check out your fix and ill play around more with the x64 menus and get back to you

**Comment by Hypnootize** [comment]
The fix is now integrated in the master branch.
